on:
  push:
  
env:
  APP_NAME: cas

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 14.x
      - name: Build
        run: npm install && npm run build

  package:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Pack
        run: touch ${{ env.APP_NAME }}.tar.gz && tar --exclude-ignore=.appignore --transform 's,^\./,${{ env.APP_NAME }}/,' -cvzf ${{ env.APP_NAME }}.tar.gz .
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.0
        with:
          name: distribution
          path: ${{ env.APP_NAME }}.tar.gz

  release:
    environment: release
    needs: package
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Upload Release
        uses: softprops/action-gh-release@v1
        id: upload_release
        with:
          files: cas.tar.gz
          prerelease: ${{ contains(github.ref, '-') }}  # following semver spec
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload app to Nextcloud appstore
        uses: R0Wi/nextcloud-appstore-push-action@a011fe619bcf6e77ddebc96f9908e1af4071b9c1
        with:
          app_name: ${{ env.APP_NAME }}
          appstore_token: ${{ secrets.APPSTORE_TOKEN }}
          download_url: ${{ steps.upload_release.outputs.url }}
          app_private_key: ${{ secrets.APP_PRIVATE_KEY }}
          nightly: ${{ steps.upload_release.inputs.prerelease }}

      - name: Delete crt and key from local storage
        run: rm -f ~/.nextcloud/certificates/*
